### PR TITLE
Reduce contention on undo_spaces_lock during undo truncation

### LINKED ISSUE #132: Reduce contention on undo_spaces_lock during undo tablespace truncation
The undo_spaces_lock is exclusively locked by the purge coordinator thread during undo tablespace truncation. A frontend thread will request a shared lock on undo_spaces_lock in order to find an available undo tablespace, which may be blocked by the purge coordinator. The contention can be reduced by synchronizing the two types of threads via atomic variables instead of rw locks.

### PR DESCRIPTION
**Pull request by zwang28**
A undo tablespaces snapshot is taken by the purge_coordinator thread while holding the xlock for undo_spaces_lock, then the frontend thread can query the snapshot without holding a slock for undo_spaces_lock.
Add 3 innodb_metrics undo_truncate_snapshot_ticket_grant_count and undo_truncate_snapshot_ticket_try_count, to monitor the atomic operation's contention during querying snapshot.

### CODE REVIEW

**Comment by zwang28** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> The following commits have not yet signed CLA.
> 
> **[52286f0](https://github.com/kunpengcompute/mysql-server/commit/52286f0c01475d9b8098e9bd08e516075019524a)** | Reduce contention on undo_spaces_lock during undo tablespace truncation.
> A undo tablespaces snapshot is taken by the purge_coordinator thread while holding the xlock for undo_spaces_lock, then the frontend thread can query the snapshot without holding a slock for undo_spaces_lock.
> Add 3 innodb_metrics undo_truncate_snapshot_ticket_grant_count, undo_truncate_snapshot_ticket_try_count and undo_truncate_snapshot_ticket_wait_count, to monitor the atomic operation's contention.
> 
> 📝 **Please access [here](https://clasign.osinfra.cn/sign/Z2l0aHViJTJGa3VucGVuZ2NvbXB1dGU=) to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment: **/check-cla** to verify. Thanks.
> 
> * If you've already signed a CLA, it's possible you're using a different email address for your gitee account. Check your existing CLA data and verify the email.
> * If you signed the CLA as an employee or a member of an organization, please contact your corporation or organization to verify you have been activated to start contributing.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please feel free to file an issue.

 /check-cla

**Comment by zwang28** [comment]
> undo::undo_spaces_snapshot 在new之后没有判空，此处使用之前也没有判空

此处new无需判空

**Comment by zwang28** [comment]
> std::vector<Tablespace *> tablespaces 可以传const引用，减少一次构造

接受

**Comment by zwang28** [comment]
> undo::spaces->m_spaces上是否只有1个space需要排除？如果undo::spaces->m_spaces的元素个数比较大的时候，这个for循环的push_back的成本需要考虑

至多一个marked_space。spaces个数至多128个。

**Comment by zwang28** [comment]
> undo_space != nullptr

接受

**Review by liuwei-ck — APPROVED** [review]

**Comment by zwang28** [comment]
> 如果快照中没有space，即唯一一个space被排除，导致需要等s锁，可以优化将undo::undo_spaces_snapshot->get_target_undo_tablespaces_size();的判断放入undo::undo_spaces_snapshot->request_ticket的实现中，快照为空就返回request_ticket false，避免request和return的while操作原子变量

必存在两个implicit undo tablespaces，至多一个marked for truncation，所以快照中必有space。

**Comment by Bessel-Native** [comment]
good job

**Review by Bessel-Native — APPROVED** [review]

**Pull request merged**
